// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyczwkikbzkjjtldsyrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Y3p3a2lrYnpramp0bGRzeXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0Nzk4NDksImV4cCI6MjA1MzA1NTg0OX0.odAIFRpHmxmSJ2gO-0TyhARaNGxQlKXaKktDnvWhHoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);